Models/FavouriteRecipe.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyRecipe.Models
{
    public class FavouriteRecipe
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public int RecipeId { get; set; }

        [Required]
        public int UserId { get; set; }


        [ForeignKey("RecipeId")]
        public virtual Recipe Recipe { get; set; }

        public virtual User User { get; set; }
    }
}

Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyRecipe.Models
{
    public class Recipe
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MinLength(3)]
        public string Name { get; set; }

        public string Description { get; set; }
        
        [Required(ErrorMessage="The Time to cook field is required.")]
        public TimeSpan TimeToCook { get; set; }

        public int Portions { get; set; }


        [Required]
        public int CategoryId { get; set; }

        [Required]
        public int CreatedBy { get; set; }

        [NotMapped]
        public bool IsFavourite { get; set; }


        public virtual Category Category { get; set; }

        [ForeignKey("CreatedBy")]
        public virtual User CreatedByUser { get; set; }

        public virtual List<RecipeImage> RecipeImages { get; set; }

        public virtual FavouriteRecipe FavouriteRecipe { get; set; }
        
        [Required]
        public virtual List<RecipeProduct> Products { get; set; }
    }
}

Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyRecipe.Models;
using MyRecipe.Data;
using MyRecipe.Data.DAOs;
using MyRecipe.Data.DTOs;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.Security.Claims;
using MyRecipe.Data.DAOs.Shared;
using System.Text.Json;

namespace MyRecipe.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class RecipeController : Controller
    {

        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILogger<RecipeController> _logger;
        private readonly MyRecipeDBContext _dbContext;
        private readonly User _authenticatedUser;
        private readonly CategoryDAO _categories;
        private readonly RecipeDAO _recipes;
        private readonly ProductDAO _products;


        public RecipeController(
            IHttpContextAccessor httpContextAccessor,
            IWebHostEnvironment webHostEnvironment,
            ILogger<RecipeController> logger,
            MyRecipeDBContext dbContext
        )
        {
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
            _dbContext = dbContext;
            _categories = new CategoryDAO(dbContext);
            _recipes = new RecipeDAO(dbContext);
            _products = new ProductDAO(dbContext);

            String username = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            _authenticatedUser = _dbContext.Users.Where(user => user.Username == username).FirstOrDefault();
        }

        [HttpGet("List")]
        public IActionResult Index(int? categoryId, [FromQuery(Name = "productIds")] string productIdsStr, string search = null, int page = 1, int itemsPerPage = 12)
        {
            ViewData["search"] = search;
            ViewData["categoryId"] = categoryId;
            ViewData["productIds"] = productIdsStr;

            RecipesCategoriesDTO data = new RecipesCategoriesDTO();
            data.Categories = _categories.GetAll();
            data.Products = _products.GetAll();

            data.SelectedCategory = (categoryId != null)
                ? data.Categories.Where(category => category.Id == categoryId).First()
                : data.Categories.First();

            data.SelectedProductIds = JsonSerializer.Deserialize<List<int>>(productIdsStr ?? "[]");

            RecipesFilterDTO recipesFilter = new RecipesFilterDTO();
            recipesFilter.CategoryId = data.SelectedCategory.Name != "All"
                ? data.SelectedCategory.Id
                : null;
            recipesFilter.ProductIds = data.SelectedProductIds;
            recipesFilter.Name = search;

            data.Recipes = _recipes.GetFiltered(this._authenticatedUser, recipesFilter, page, itemsPerPage);
            return View(data);
        }

        [HttpGet("{recipeId}/Details")]
        public IActionResult RecipeDetails(int recipeId)
        {
            RecipeDetailsDTO recipeDetails = _recipes.GetDetails(this._authenticatedUser, recipeId);
            return View("RecipeDetails", recipeDetails);
        }


        [HttpGet("MyRecipes")]
        public IActionResult UserRecipes(UserRecipesDTO data, string search = null, int page = 1, int itemsPerPage = 12)
        {
            ViewData["search"] = search;
            data = new UserRecipesDTO();
            RecipesFilterDTO recipesFilter = new RecipesFilterDTO();
            recipesFilter.Name = search;
            recipesFilter.CreatedByUserId = this._authenticatedUser.Id;
            data.UserRecipes = _recipes.GetFiltered(this._authenticatedUser, recipesFilter, page, itemsPerPage);

            data.NewRecipe = new CreateRecipeDTO()
            {
                Categories = _categories.GetAll(false),
                Products = _products.GetAll(),
                MeasurementUnits = _products.GetMeasurementUnits()
            };

            return View("UserRecipes", data);
        }

        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult CreateRecipe(CreateRecipeDTO newRecipe)
        {
            if (ModelState.IsValid)
            {
                newRecipe.Recipe.CreatedBy = this._authenticatedUser.Id;
                this._dbContext.Recipes.Add(newRecipe.Recipe);

                if (newRecipe.RecipeImages != null && newRecipe.RecipeImages.Count() > 0)
                {
                    bool primaryImage = true;
                    foreach (var imageFile in newRecipe.RecipeImages)
                    {
                        string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "img/Recipe");
                        string fileName = Guid.NewGuid().ToString() + "_" + imageFile.FileName;
                        string filePath = Path.Combine(uploadDir, fileName);

                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            imageFile.CopyTo(fileStream);
                        }

                        RecipeImage recipeImage = new RecipeImage()
                        {
                            Recipe = newRecipe.Recipe,
                            ImagePath = fileName,
                            IsPrimary = primaryImage
                        };

                        this._dbContext.RecipeImages.Add(recipeImage);
                        primaryImage = false;
                    }
                }

                this._dbContext.SaveChanges();
            }

            return RedirectToAction("UserRecipes");
        }

        [HttpGet("Form/AddProduct")]
        public IActionResult CreateEditRecipeAddProduct(CreateRecipeDTO data)
        {
            data.Categories = _categories.GetAll(false);
            data.Products = _products.GetAll();
            data.MeasurementUnits = _products.GetMeasurementUnits();
            data.Recipe.Products.Add(new RecipeProduct());

            ModelState.Clear();

            return PartialView("_CreateEditRecipePartial", data);
        }

        [HttpGet("{recipeId}/Edit")]
        public IActionResult GetEditRecipeModal(int recipeId)
        {
            CreateRecipeDTO data = new CreateRecipeDTO()
            {
                Recipe = _recipes.GetById(recipeId, true),
                Categories = _categories.GetAll(false),
                Products = _products.GetAll(),
                MeasurementUnits = _products.GetMeasurementUnits()
            };

            if (data.Recipe.RecipeImages == null) {
                data.Recipe.RecipeImages = new List<RecipeImage>();
            }

            return PartialView("_CreateEditRecipePartial", data);
        }

        [HttpPost("{recipeId}/Edit")]
        [ValidateAntiForgeryToken]
        public IActionResult EditRecipe(CreateRecipeDTO newRecipeData)
        {
            Recipe recipe = _recipes.GetById(newRecipeData.Recipe.Id, true);
            if (recipe.CreatedBy != _authenticatedUser.Id)
            {
                Forbid();
            }

            recipe.Name = newRecipeData.Recipe.Name;
            recipe.CategoryId = newRecipeData.Recipe.CategoryId;
            recipe.Products = newRecipeData.Recipe.Products;
            recipe.TimeToCook = newRecipeData.Recipe.TimeToCook;
            recipe.Portions = newRecipeData.Recipe.Portions;
            recipe.Description = newRecipeData.Recipe.Description;


            if (newRecipeData.RecipeImages != null && newRecipeData.RecipeImages.Count() > 0)
            {
                foreach (RecipeImage recipeImage in recipe.RecipeImages)
                {
                    string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "img/Recipe");
                    string filePath = Path.Combine(uploadDir, recipeImage.ImagePath);
                    if (System.IO.File.Exists(filePath))
                    {
                        System.IO.File.Delete(filePath);
                        this._dbContext.RecipeImages.Remove(recipeImage);
                    }
                }

                bool primaryImage = true;
                foreach (var imageFile in newRecipeData.RecipeImages)
                {
                    string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "img/Recipe");
                    string fileName = Guid.NewGuid().ToString() + "_" + imageFile.FileName;
                    string filePath = Path.Combine(uploadDir, fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        imageFile.CopyTo(fileStream);
                    }

                    RecipeImage recipeImage = new RecipeImage()
                    {
                        RecipeId = recipe.Id,
                        ImagePath = fileName,
                        IsPrimary = primaryImage
                    };

                    recipe.RecipeImages.Add(recipeImage);
                    primaryImage = false;
                }
            }


            this._dbContext.Update(recipe);
            this._dbContext.SaveChanges();

            return RedirectToAction("RecipeDetails", new { recipeId = newRecipeData.Recipe.Id });
        }

        [HttpPost("{recipeId}/Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteRecipe(int recipeId)
        {
            Recipe recipe = _recipes.GetById(recipeId, true);
            if (recipe.CreatedBy != _authenticatedUser.Id)
            {
                Forbid();
            }



Views/Recipe/FavouriteRecipes.cshtml
@model MyRecipe.Data.DAOs.Shared.PaginatedList<MyRecipe.Data.DTOs.RecipeDTO>
@{
  ViewData["Title"] = "My Recipes";
  var search = ViewData["search"];
}

<div class="d-flex flex-row vh-94 overflow-auto">
  <div class="container pt-4">
    <div class="row mx-1 justify-content-between">
      <div class="col-lg-6 align-self-center align-center">
        <h4 class="mb-0 me-2 d-inline-block">Favourite recipes</h4>
      </div>
      <div class="col-lg-4">
        <form asp-action="FavouriteRecipes" method="GET">
          <div class="input-group">
            <input type="text" name="search" value="@search" class="form-control" placeholder="Search a recipe . . ."
              aria-label="recipe" aria-describedby="button-addon" />
            <input type="submit" class="btn btn-primary" id="button-addon" value="Search" />
            <button type="button" onclick="RedirectToPage(1, true)" class="btn btn-secondary"
              id="button-addon2">Clear</button>
          </div>
        </form>
      </div>
    </div>


      <div class="row justify-content-start pt-4">
        @foreach (var recipe in Model)
        {
          <div class="col mx-1 pt-3 recipe-card-container">
            <partial name="_RecipePartial" model="recipe" />
          </div>
        }
      </div>
      <partial name="_PaginationPartial" model="@Model" />
  </div>
</div>

Views/Recipe/Index.cshtml
@model MyRecipe.Data.DTOs.RecipesCategoriesDTO
@{
    ViewData["Title"] = "All Recipes";
    string search = ViewData["search"] as string;
    string productIds = ViewData["productIds"] as string;
    var categoryId = ViewData["categoryId"];
}

<div class="d-flex flex-row vh-94 overflow-auto">
    <div class="col-2 sticky-top sidebar bg-light pt-2">
        @* <h5 class="ps-2">Filter</h5> *@
        <h7 class="ps-2 sm-hide">Categories</h7>
        <nav class="navbar navbar-light">
            <div class="container-fluid">
                <ul class="navbar-nav w-100">
                    @foreach (var category in Model.Categories)
                    {
                            <li class="nav-item d-flex category-menu-item" onclick="FilterRecipesByCategory(@category.Id)">
                                <div class="col hover-pointer flex-grow-0 align-self-center @(category.Id == Model.SelectedCategory.Id ? "nav-img-active" : "")">
                                @{
                                    string imagePath = "~/img/Category/" + category.ImagePath;
                                }
                                    <img src=@imagePath class="" asp-append-version />
                                </div>
                                <div
                            class="col ps-2 sm-hide hover-pointer align-self-center nav-link @(category.Id == Model.SelectedCategory.Id ? "active" : "")">
                                @category.Name
                                </div>
                            @if (category.Id == Model.SelectedCategory.Id)
                            {
                                        <span class="ms-auto sm-hide nav-link active align-self-center">
                                            <i class="far fa-check"></i>
                                        </span>
                            }
                            </li>
                    }
                </ul>
            </div>
        </nav>
        <h7 class="ps-2 sm-hide">Products</h7>
        <div class="pt-2 px-3">
        <select id="recipeProductSelect" multiple class="form-select" size="10">
                @foreach (var product in @Model.Products)
                {
                <option 
                value="@product.Id"
                selected="@Model.SelectedProductIds.Contains(@product.Id)"
                onclick="FilterRecipesByProduct(this.value)"
            >@product.Name</option>
                }   
      </select>
      </div>
    </div>
    <div class="col-10">
        <div class="container pt-4">
            <div class="row justify-content-between mx-1">
                <div class="col-lg-6 align-self-center align-center">
                    <h4 class="mb-0 me-2 d-inline-block">@Model.SelectedCategory.Name</h4>
                </div>
                <div class="col-lg-4">
                    <form asp-action="Index" method="GET">
                        <div class="input-group">
                            <input type="text" name="search" value="@search" class="form-control" placeholder="Search a recipe . . ."
                            aria-label="recipe" aria-describedby="button-addon" />
                            <input type="submit" class="btn btn-primary" id="button-addon" value="Search" />
                            <button type="button" onclick="RedirectToPage(1, true)" class="btn btn-secondary"
                            id="button-addon2">Clear</button>

                        </div>
                        <input type="hidden" name="productIds" value="@productIds" />
                        <input type="hidden" name="categoryId" value="@categoryId" />
                    </form>
                </div>
            </div>

            <div class="row justify-content-start pt-4">
                @foreach (var recipe in Model.Recipes)
                {
                    <div class="col mx-1 pt-3 recipe-card-container">
                        <partial name="_RecipePartial" model="recipe" />
                    </div>
                }
            </div>
        <div class="mx-1">
          <partial name="_PaginationPartial" model="@Model.Recipes" />
          </div>
        </div>
    </div>
</div>

Views/Recipe/RecipeDetails.cshtml
@using System.Security.Claims
@using MyRecipe.Data.DTOs
@model MyRecipe.Data.DTOs.RecipeDetailsDTO
@{
	ViewData["Title"] = "MyRecipe - " + @Model.Name;
	int primaryImageIndex = Model.Images.FindIndex(image => image.IsPrimary = true);
	string currentUser = ((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.NameIdentifier).Value;
}

<div class="d-flex flex-row vh-94 overflow-auto">
	<div class="container">
		<div class="pb-4 pt-4">
			<div id="carouselControls" class="carousel carousel-dark slide pt-4" data-bs-ride="carousel">
				<div class="carousel-inner">
					@if (Model.Images.Count() > 0)
					{
						@for (var index = 0; index < Model.Images.Count(); index++)
						{
							string imagePath = "/img/Recipe/" + Model.Images[index].ImagePath;
							string activeImageClass = index == primaryImageIndex ? "active" : "";

							<div class="carousel-item @activeImageClass">
								<img src="@imagePath" class="carousel-image d-block w-100">
							</div>
						}
					}
					else
					{
						<div class="carousel-item active">
							<img src="/img/Recipe/no-recipe.png" class="carousel-image d-block w-100">
						</div>
					}
				</div>
				<button class="carousel-control-prev" type="button" data-bs-target="#carouselControls"
					data-bs-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="visually-hidden">Previous</span>
				</button>
				<button class="carousel-control-next" type="button" data-bs-target="#carouselControls"
					data-bs-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="visually-hidden">Next</span>
				</button>
			</div>

			<div class="row justify-content-between border-bottom border-2 pt-4">
				<div class="col">
					<table>
						<tr>
							<td class="h5 mb-0" rowspan="3">
								<img class="me-1" src="/img/Category/@Model.Category.ImagePath" width="40" height="50">
							</td>
						</tr>
						<tr>
							<td class="h5 mb-0 lh-20">
								@Model.Name
							</td>
							<td rowspan="3" class="pb-2">
								@if (Model.CreatedBy == @currentUser)
								{
									<i data-bs-toggle="tooltip" data-bs-placement="top" title="Edit recipe"
									class="fal fa-pen fs-27 ms-3 hover-pointer icon-hover-color"
									onclick="ShowEditRecipeModal(@Model.Id)"></i>

									<form class="d-inline-block" method="POST" asp-controller="Recipe"
									asp-action="DeleteRecipe" asp-route-recipeId="@Model.Id">
										<i data-bs-toggle="tooltip" data-bs-placement="top" title="Delete recipe"
										class="fal fa-trash-alt fs-27 ms-2 hover-pointer icon-hover-color"
										onclick="ShowDeleteConfirmationModal(this, 'Delete recipe', 'Are you sure you want to delete recipe \'@Model.Name\'?')">
										</i>
									</form>
								}
								@if (Model.FavouriteToCurrentUser)
								{
									<i data-bs-toggle="tooltip" data-bs-placement="top" title="Remove from favourites"
									class="fas fa-heart fs-27 text-danger ms-2 hover-pointer add-to-favourites-hover-color"
									onclick="RemoveRecipeFromFavourites(@Model.Id)"></i>
								}
								else
								{
									<i data-bs-placement="top" title="Add to favourites"
									class="fal fa-heart fs-27 text-danger ms-2 hover-pointer add-to-favourites-hover-color"
									onclick="AddRecipeToFavourites(@Model.Id)"></i>
								}
							</td>
						</tr>
						<tr>
							<td class="lh-20"><small><i class="far fa-user mb-2 me-1"></i>@Model.CreatedBy</small></td>
						</tr>
					</table>
				</div>
				<div class="col-auto">
					<table>
						<tr>
							<td class="h5 mb-0" rowspan="3"><i class="fal fa-utensils fa-lg me-2"></i></td>
						</tr>
						<tr>
							<td class="h5 mb-0 lh-20">Portions</td>
						</tr>
						<tr>
							<td class="lh-20"><small>@Model.Portions</small></td>
						</tr>
					</table>
				</div>
				<div class="col-auto">
					<table>
						<tr>
							<td class="h5 mb-0" rowspan="3"><i class="fal fa-clock fa-lg me-2"></i></td>
						</tr>
						<tr>
							<td class="h5 mb-0 lh-20">Time</td>
						</tr>
						<tr>
							<td class="lh-20"><small>@Model.TimeToCook</small></td>
						</tr>
					</table>
				</div>
			</div>
			<div class="p-4">
				@if (Model.Products.Count() > 0)
				{
					<h5>Ingredients</h5>
					@foreach (var product in Model.Products)
					{
						<div class="ps-2">
							<input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
							<label class="form-check-label" for="flexSwitchCheckDefault">@product.Quantity @product.Unit
								@product.Name</label>
						</div>
					}
				}

				@if (Model.Description != null && Model.Description.Length > 0)
				{
					<h5 class="pt-4">Description</h5>
					<div class="ps-2">
						@Model.Description
					</div>
				}
			</div>
		</div>
	</div>
</div>

<div id="editRecipeModal" class="modal mt-5">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Edit recipe</h5>
				<button type="button" class="btn-close" onclick="HideEditRecipeModal()" aria-label="Close">
					<span aria-hidden="true"></span>
				</button>
			</div>
			<div class="modal-body">
				<partial name="_CreateEditRecipePartial" model="new CreateRecipeDTO()" />
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" onclick="SubmitRecipeForm()">Save</button>
				<button type="button" class="btn btn-secondary" onclick="HideEditRecipeModal()">Close</button>
			</div>
		</div>
	</div>
</div>

<partial name="_DeleteConfirmationModalPartial" />

Views/Recipe/UserRecipes.cshtml
@model MyRecipe.Data.DTOs.UserRecipesDTO
@{
	ViewData["Title"] = "My Recipes";
	var search = ViewData["search"];
}

@* <div class="container-fluid sticky-top">
	<div class="row justify-content-between py-3 "> *@
<div class="d-flex flex-row vh-94 overflow-auto">
	<div class="container pt-4">
		<div class="row mx-1 justify-content-between">
			<div class="col-lg-6 align-self-center align-center">
				<h4 class="mb-0 me-2 d-inline-block">My recipes</h4>
				<button class="btn btn btn-outline-primary" onclick="ShowCreateRecipeModal()"> <i
						class="ml-5 fal fa-plus"></i>
					Create recipe</button>
			</div>
			<div class="col-lg-4 pe-0">
				<form asp-action="UserRecipes" method="GET">
					<div class="input-group">
						<input type="text" name="search" value="@search" class="form-control"
							placeholder="Search a recipe . . ." aria-label="recipe" aria-describedby="button-addon" />
						<input type="submit" class="btn btn-primary" id="button-addon" value="Search" />
						<button type="button" onclick="RedirectToPage(1, true)" class="btn btn-secondary"
							id="button-addon2">Clear</button>
					</div>
				</form>
			</div>
		</div>

			<div class="row justify-content-start pt-4">
				@foreach (var recipe in Model.UserRecipes)
				{
					<div class="col mx-1 pt-3 recipe-card-container">
						<partial name="_RecipePartial" model="recipe" />
					</div>
				}
			</div>
			<partial name="_PaginationPartial" model="@Model.UserRecipes" />
	</div>
</div>


<div id="createRecipeModal" class="modal mt-5">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Create recipe</h5>
				<button type="button" class="btn-close" onclick="HideCreateRecipeModal()" aria-label="Close">
					<span aria-hidden="true"></span>
				</button>
			</div>
			<div class="modal-body">
				<partial name="_CreateEditRecipePartial" model="@Model.NewRecipe" />
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" onclick="SubmitRecipeForm()">Create</button>
				<button type="button" class="btn btn-secondary" onclick="HideCreateRecipeModal()">Close</button>
			</div>
		</div>
	</div>
</div>